[package]
name = "csi"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints.rust]
# unused = "allow"
# unused_variables = "allow"
# unused_imports = "allow"
# dead_code = "allow"
# unused_mut = "allow"
