[general]
program_name = "CSI"
program_desc = "This is the description of my cool program!"

[[pages]]
Welcome = { title = "Welcome title", desc = "Welcome to my cool program installer."}
[[pages]]
License.title = "Accept license NOW!"
License.text = "Some boring stuff here..."
License.file_path = "samples/LICENSE"
# License.prefer_file = false
